### ISSUE TITLE
nestedInput issue with Cake 3.3.13

### ISSUE THREAD

**Issue by kyleweishaupt** [Holt59/cakephp3-bootstrap-helpers#100]
The latest CakePHP version (3.3.13) has the change `The nestedInput option in FormHelper::input() no longer appears as an attribute.`

This is causing the notice `Notice (8): Undefined index: input [ROOT\vendor\holt59\cakephp3-bootstrap-helpers\src\View\Helper\BootstrapFormHelper.php, line 408]`

Here's a basic checkbox that I'm having an issue with:
```
echo $this->Form->input(
    'RememberMe',
    [
        'type' => 'checkbox',
        'default' => true
    ]
);
```

Adding the option `nestedInput => false` causes the notice to be suppressed, but doesn't generate the checkbox input.

**Comment by Holt59** [comment]
I cannot reproduce the error with a fresh CakePHP 3.3.13 installation, and the error looks strange since line 408 of `BootstrapFormHelper.php` has nothing to do with checkbox...

Maybe you do not have the latest version of the helpers?

**Comment by Holt59** [comment]
I just checked the latest tagged version (3.0.5), and the 408th line of `BootstrapFormHelper` effectively contains a `"input"` indexing , so I think you are using this version. Update to the latest version and the problem should be fixed.

```
holt59/cakephp3-bootstrap-helpers:dev-master
```

**Comment by kyleweishaupt** [comment]
Yup - it was just the older release that was causing it. Everything works correctly now. Thank you for the response! Sorry I should have included my version earlier.
