### ISSUE TITLE
Missing documentation for on `BootstrapNavbarHelper`

### ISSUE THREAD

**Issue by curtisgibby** [Holt59/cakephp3-bootstrap-helpers#102]
I had to dig around a bit in your issues history to find [your example of using the navbar helper](https://github.com/Holt59/cakephp3-bootstrap-helpers/pull/40#issuecomment-123795894). It would be useful to have this information on the [main documentation page](https://holt59.github.io/cakephp3-bootstrap-helpers/).

**Comment by Holt59** [comment]
I am working on a new documentation written in Markdown and using mkdocs to generate the HTML. Feel free to contribute: https://github.com/Holt59/cakephp3-bootstrap-helpers/tree/mkdocs

**Comment by Holt59** [comment]
New documentation is now live with the Navbar example:

https://holt59.github.io/cakephp3-bootstrap-helpers/navbar-helper/basics/
