### ISSUE TITLE
[RFC] UrlComparerTrait::normalize including action parameters?

### ISSUE THREAD

**Issue by raul338** [Holt59/cakephp3-bootstrap-helpers#110]
I have a navbar with 4 links, 3 of them are links to the Pages Controller (to display different pages)
Up to the 3.1.0 launch the url detection worked well, after the update all PagesController link are marked as visited.
Example (simplified w/o icons)
```php
echo $this->Navbar->beginMenu();
echo $this->Navbar->link(__('Home'), [
    'controller' => 'Pages',
    'action' => 'display', 'home'
]);
echo $this->Navbar->link(__('Apartments'), [
    'controller' => 'Apartments',
    'action' => 'index'
]);
echo $this->Navbar->link(__('FAQ'), [
    'controller' => 'Pages',
    'action' => 'display', 'faq'
]);
echo $this->Navbar->link(__('General Conditions'), [
    'controller' => 'Pages',
    'action' => 'display', 'general-conditions'
]);
echo $this->Navbar->endMenu();
```
![screenshot_20170218_010538](https://cloud.githubusercontent.com/assets/7199046/23090188/66937fdc-f576-11e6-9a82-2b46848bfeee.png)

I can submit a PR to fix this, but some tests breaks, some are obvious, some others not like
```
1) Bootstrap\Test\TestCase\View\Helper\UrlComparerTraitTest::testFullBase
/cakephp/cakephp/admin/users/edit/1 != /cakephp/admin/users/edit
Failed asserting that false is true.
```
I think it should pass, but then I think how useful is a very specific link in a navbar...

Should I submit the PR? I would like have some consensus about it.

**Comment by Holt59** [comment]
This was something I was worried about when designing the URL comparer, but when you use pass parameters in your action

**Comment by Holt59** [comment]
This was something I was worried about when designing the comparer, unfortunately both your parameters (faq, home, ...) and the edit parameters (1) are treated in the same way by Cake...

One possibility would be to allow full or partial comparison, I will see if I can come up with something.

**Comment by Holt59** [comment]
I have just pushed a "fix" to the `master` branch (not the 3.1.0 tag), you can try it by requesting the `dev-master` branch.

The new behavior is basically:

> `UrlComparerTrait::compareUrls` now check if the left URL is a parent of the right URL.

This should solve both issue because:

- `/pages/home` is not a parent of `/pages/faq`;
- `/admin/users/edit` is a parent of `/admin/users/edit/1`.

Let me know if it solves your problem without creating new ones... ;)

**Comment by raul338** [comment]
Thank you, It works :clap: :clap: 

It could be better if you could specify such parent-checking in the 4th parameter of NavbarHelper::link()
So one could do this
```php
echo $this->Navbar->link(__('Dashboard'), [
    'controller' => 'Moderators',
    'action' => 'dashboard'
]);
echo $this->Navbar->link(
    __('Apartments'),
    [
        'controller' => 'Apartments',
        'action' => 'index'
    ],
    // I managed this way since the very firsts days of NavbarHelper
    [], // ['class' => $this->name == 'Apartments' ? 'active' : ''],
    [
        'escape' => false,
        'active-sub-url' => true, // add "active" class if matches /apartments/*
    ]
);
```

Anyway, You can close the issue. Thanks again

**Comment by Holt59** [comment]
I have pushed another commit to add more flexibility. The default behavior of the `autoActiveLink` is to compare whole parts of the URL, so (right column is `X` if comparison returns `true`):

| Link URL | Normalized | Current URL | Normalized |  |
|----------|-------------|--------------|-------------|--------------|
| `['controller' => 'Pages', 'action' => 'display', 'faq']` | `/pages/display/faq` | `/pages/faq` | `/pages/display/faq` | X |
| `['controller' => 'Pages', 'action' => 'display', 'faq']` | `/pages/display/faq` | `/pages/credots` | `/pages/display/credits` |  |
| `['controller' => 'Users', 'action' => 'edit']` | `/users/edit` | `/users/edit/1` | `/users/edit/1` | X  |

But you can pass an array as the `active` options to the `link` method (the second param), typically:

```php
echo $this->Navbar->link(
    __('Apartments'),
    [
        'controller' => 'Apartments',
        'action' => 'index'
    ],
    ['active' => ['action' => false, 'pass' => false]]
);
```

Now:

| Link URL | Normalized | Current URL | Normalized |  |
|----------|-------------|--------------|-------------|--------------|
| `['controller' => 'Apartments', 'action' => 'index']` | `/apartments` | `/apartments/action` | `/apartments/action` | X |

The current URL will never be altered by the option, only the link URL is modified.

I will add more information to the documentation when I have time.

**Comment by Holt59** [comment]
I have added this to the documentation:

http://holt59.github.io/cakephp3-bootstrap-helpers/navbar-helper/auto-active-link/

I am closing this, feel free to (re-)open if you have any troubles!
