### ISSUE TITLE
Where to define the templates

### ISSUE THREAD

**Issue by dype35** [Holt59/cakephp3-bootstrap-helpers#111]
It's just a question:

Where is the best place to put : 
`$this->Html->templates(['icon' => '<i class="fa fa-{{type}}"></i>']);`

Thanks

**Comment by Holt59** [comment]
If you want to use Font Awesome everywhere, the best way is to directly set the template when loading the helper, e.g. in your `AppView`:

```php
$this->loadHelper('Html', [
    'className' => 'Bootstrap.Html',
    'templates' => [
        'icon' => '<i class="fa fa-{{type}}"></i>'
    ]
]);
```

---

Or if you load the helper in a controller:

```php
public $helpers = [
    'Html' => [
        'className' => 'Bootstrap.Html',
        'templates' => [
            'icon' => '<i class="fa fa-{{type}}"></i>'
        ]
    ]
];
```

**Comment by dype35** [comment]
thanks

**Comment by rifton007** [comment]
I tried, but not working for me. No change, all keep with glyphicon.

CakePHP 3.5.1
Bootstrap 3.3.7
FontAwesome 4.7

``` php
// AppView.php
public function initialize() {
    $this->loadHelper('Html', [
        'className' => 'Bootstrap.BootstrapHtml',
        'templates' => [
            'icon' => '<i class="fa fa-{{type}}"></i>'
        ]
    ]);
    $this->loadHelper('Form', [
        'className' => 'Bootstrap.BootstrapForm',
    ]);
}
```

I also tried that:
``` php
// myView.ctp
echo $this->Html->icon('home');
$this->Html->templates([
    'icon' => '<i class="fa fa-{{type}}{{attrs.class}}"{{attrs}}></i>'
]);
echo $this->Html->icon('home');
```

Thanks,

**Comment by Holt59** [comment]
I cannot reproduce - Which version of the helpers are you using? Can you verify that the generated DOM is really the glyphicon one?

**Comment by rifton007** [comment]
Really sorry that's my mistake, I had installed version 3.0.7 of the plugin.
