### ISSUE TITLE
PanelHelper - add option to specify the initial state of collapsable panel

### ISSUE THREAD

**Issue by Antoniossss** [Holt59/cakephp3-bootstrap-helpers#113]
Hey 

Right now following code
`<?= $this->Panel->create("Filters", ["collapsible" => true]) ?>`
will output collapsable panel that is initially open. Additional option for initial state would be very usefull. Another aproach would be to add consider integer value for `collapsible` so 0 = false, 1 true, initially open, >1 true, initially closed.

**Comment by Holt59** [comment]
There is already a `open` option, you should be able to do:

```php
echo $this->Panel->create('Filters', ['collapsible' => true, 'open' => false]);
```

If this does not work, this is a bug.

**Comment by Antoniossss** [comment]
I was convinced that I have already checked that out, but I was obviously wrong. I dont know why did I missed that reading the source code :( 
Sorry for troubles. `open` option works as expected.

**Comment by Holt59** [comment]
No problem, the documentation has been updated recently and is now much more complete so you may find relevant information without having to look at the sources:

- new sections regarding panels: 

> https://holt59.github.io/cakephp3-bootstrap-helpers/panel-helper/basics/

- API documentation of the panel helper: 

> https://holt59.github.io/cakephp3-bootstrap-helpers/api/class-Bootstrap.View.Helper.PanelHelper.html

**Comment by Antoniossss** [comment]
Thank you, keep up the good work.
