### ISSUE TITLE
date input missing row

### ISSUE THREAD

**Issue by krsriq** [Holt59/cakephp3-bootstrap-helpers#115]
When using date inputs (`$this->Form->input('date', ['type' => 'date'])`) the markup created misses a `<div class="row">` around the select box columns. The same is true for input type year.
Confirmed on fresh install of Cake v3.4.2.

**Comment by Holt59** [comment]
Should be fixed by d236cd3d8766bc1aca2b066734df2cb1051e4e5f, let me know if it works for you - if it does not, could you elaborate on the expected behavior (by providing the expected markup)? Thanks.

**Comment by krsriq** [comment]
Great, fixed! Thanks a lot!

**Comment by Holt59** [comment]
I am closing this, do not hesitate to open a new issue if necessary!
