### ISSUE TITLE
Modal size broken?

### ISSUE THREAD

**Issue by mferak** [Holt59/cakephp3-bootstrap-helpers#117]
Hi!
When trying to create a modal with the size option "lg", the markup seems to be wrong.

According to bootstrap's documentation, it should be 

```
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      ...
    </div>
  </div>
</div>
```

but what I get instead is

```
<div class="modal fade modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      ...
    </div>
  </div>
</div>
```

The resulting modal is not large, and positioned off-center to the left.

Is there an easy way to fix this?

PS: Thanks for the great plugin.

**Comment by Holt59** [comment]
I think Bootstrap change the target for the class in a recent version. I'll push a fix as soon as I can (this is an easy fix but I do not have access to a working dev environment right now).

**Comment by Holt59** [comment]
Should be fixed by ba8cb3f9e763ab3cba1dd7ede35e5b64b080bb81.

**Comment by mferak** [comment]
Thank you so much!

**Comment by Holt59** [comment]
I am closing this, feel free to open a new issue if you have any problem!
