### ISSUE TITLE
HtmlHelper::dropdown() deprecated

### ISSUE THREAD

**Issue by ypnos-web** [Holt59/cakephp3-bootstrap-helpers#118]
Thanks for your terrific work on the new version of the helpers and cakephp 3.4 support!

You deprecated the dropdown() method. FormHelper::dropdownButton() is using it, but not deprecated yet.

Will there be an alternative to the deprecated method? What is the rationale behind the deprecation?

Thanks!

**Comment by Holt59** [comment]
I marked it deprecated in a previous version because I did not like the way it was working (passing the inputs as an array of array... ), but I have now modified it so it should not be marked as deprecated, I will fix that.

**Comment by Holt59** [comment]
Fixed by 598416f73bdf374c0fe691146663944a143afa43 in `master` and `v3.1.2` branch, sorry for the inconvenience.
