### ISSUE TITLE
Choose where the error will be displayed

### ISSUE THREAD

**Issue by danielfpedro** [Holt59/cakephp3-bootstrap-helpers#122]
Will be nice if we can choose where to display the error. In the space right the input or under the input.
Now we just can do that puting the `error => 0` but we need set the input size to complete the 12 so the input get too much wider.

**Comment by Holt59** [comment]
You don't have to set the total size to 12 if you set `error` to 0. Could you please elaborate on the problem (if possible give a non-working example)?

**Comment by Holt59** [comment]
Closing this, feel free to re-open if my previous comment did not answer your question.
