### ISSUE TITLE
Tooltips with class argument

### ISSUE THREAD

**Issue by ypnos-web** [Holt59/cakephp3-bootstrap-helpers#124]
The `HtmlHelper::tooltip()` method wraps content in an element and adds attributes necessary for bootstrap tooltips.

I would expect the method to also accept 'class' etc. options and pass them through so they end up in the HTML (as most methods do, e.g. tag(), div(), para(), etc.).

However I didn't really understand how to change the code of tooltip() to make it work.

**Comment by Holt59** [comment]
The `tooltip()` method should already do that, but I have just noticed the template is incorrect:

```php
'tooltip' => '<{{tag}} data-toggle="{{toggle}}" data-placement="{{placement}}" title="{{tooltip}}">{{content}}</{{tag}}>'
```

There is a missing `{{attrs}}` placeholder, so the template should be:

```php
'tooltip' => '<{{tag}} data-toggle="{{toggle}}" data-placement="{{placement}}" title="{{tooltip}}">{{content}}</{{tag}}>'
```

**Comment by Holt59** [comment]
I closed this by mistake, sorry...

**Comment by ypnos-web** [comment]
No worries, pull request is coming up.
