### ISSUE TITLE
Easy icon can't be used in HTML link

### ISSUE THREAD

**Issue by titamrtn** [Holt59/cakephp3-bootstrap-helpers#128]
I've tried to use easy icon when creatin link but it does not work
`<?php
    echo $this->Html->link('i:dashboard Dashboard',['controller' => 'Home', 'action' => 'dashboard']);
?>`
And i got this result
`<a href="/home/dashboard">i:dashboard Dashboard</a>`

**Comment by Holt59** [comment]
This is not currently supported, but could be easily added, I will see if I can do something about this.

**Comment by titamrtn** [comment]
Thank you

**Comment by Holt59** [comment]
4e69b5c6b2b0016f70c67ad56429c81f0ca920b3 should add easy icon support to `HtmlHelper::link`.

**Comment by Holt59** [comment]
I am closing this since this should be working, if you find any bug with this feature or another one, feel free to open a new issue!
