### ISSUE TITLE
Panel groups inside panel does not work

### ISSUE THREAD

**Issue by Antoniossss** [Holt59/cakephp3-bootstrap-helpers#133]
So i have following markup:
```

    echo $this->Panel->create(__("Assignment rules for user {0}", $user->display));
    echo $this->Panel->startGroup(["collapsible" => true]);
    echo $this->Panel->create("Rule NO 1");
    echo "Rule 1";
    echo $this->Panel->end();
    echo $this->Panel->create("Rule NO 2");
    echo "Rule 2";
    echo $this->Panel->end();
    echo $this->Panel->endGroup();
    echo $this->Panel->end();
```

and This is what happening:
![obraz](https://user-images.githubusercontent.com/7877627/27224152-e57a308c-5293-11e7-9f7d-a52b6bae14cf.png)

Removing top level panel fixes exerything and accordian works fine.

**Comment by Holt59** [comment]
Unfortunately `PanelHelper` are not stateless, so you cannot create a panel or a group inside another one... 

Modifying the `Helper` to work like that would require a non-negligible amount of work, so I am not sure I will update it, but you can do either of the following:

### Create the inner panel before the panel:

```php
$panel1 = "";
$panel1 .= $this->Panel->startGroup(["collapsible" => true]);
$panel1 .= $this->Panel->create("Rule NO 1");
$panel1 .= "Rule 1";
$panel1 .= $this->Panel->end();
$panel1 .= $this->Panel->create("Rule NO 2");
$panel1 .= "Rule 2";
$panel1 .= $this->Panel->end();
$panel1 .= $this->Panel->endGroup();

echo $this->Panel->create(__("Assignment rules for user {0}", $user->display));
echo $panel1;
echo $this->Panel->end();
```

### Use another instance of `PanelHelper`:

```php
$panel = new \Bootstrap\View\Helper\PanelHelper($this);

echo $this->Panel->create(__("Assignment rules for user {0}", $user->display));

echo $panel->startGroup(["collapsible" => true]);
echo $panel->create("Rule NO 1");
echo "Rule 1";
echo $panel->create("Rule NO 2");
echo "Rule 2";
echo $panel->endGroup();

echo $this->Panel->end();
```

**Comment by Antoniossss** [comment]
@Holt59 I have buffered inner content and echoed it later just like you mentioned. Thanks for the tips.

**Comment by Holt59** [comment]
This has been merged onto `master`, I am closing this issue, feel free to open a new one if you still have troubles with these helpers.
