### ISSUE TITLE
Error on $this->Panel->footer();

### ISSUE THREAD

**Issue by dype35** [Holt59/cakephp3-bootstrap-helpers#136]
Salut Mikaël

I use this plugin since a couple of month with no problem.
I've uptated with the last release today, and now I have an error on $this->Panel->footer() : 

 `Call to undefined method Bootstrap\Utility\StackedStates::setCurrent()`
`Error in: ROOT/vendor/holt59/cakephp3-bootstrap-helpers/src/View/Helper/PanelHelper.php, line 474`

Maybe I missed something with the new version?

Thanks

**Comment by Holt59** [comment]
This was due to a bug with the new system, this should be fixed by 84f0ba4677ddb7e7399f10ba0fdbb19c212eab6c.

**Comment by dype35** [comment]
Yes, thanks
