### ISSUE TITLE
Placeholder on input file?

### ISSUE THREAD

**Issue by alphp** [Holt59/cakephp3-bootstrap-helpers#137]
Is it possible to define a placeholder for the input file?

**Comment by Holt59** [comment]
For the custom input file, you can use the `_input` option, e.g.:

```php
echo $this->Form->file('fieldname', [
    '_input' => [
        'placeholder' => 'My placeholder'
    ]
];
```

There are two special options `_input` and `_button`  that can be used to customize the input and the button.

For the standard file input, you will have to check the CakePHP documentation, but I don't think it is a supported HTML feature.

**Comment by alphp** [comment]
Great, thank's a lot
