### ISSUE TITLE
Question : 2 releases in the same application

### ISSUE THREAD

**Issue by dype35** [Holt59/cakephp3-bootstrap-helpers#145]
Hello

I'd like to know if it is possible to have the bootstrap 3 and the bootstrap 4 releases in the same application ?

In my application, front office is with bootstrap 3 and back office with bootstrap 4.

Thanks

**Comment by Holt59** [comment]
I don't know - This was possible in CakePHP 2 by loading manually the plugin... This may still be possible but you could have clashes regarding namespace, so you would need to conditionally load a version.

You should ask this to the CakePHP team, or on stackoverflow (with the `cakephp` tag).

**Comment by dype35** [comment]
thanks

**Comment by Holt59** [comment]
This could help you: https://stackoverflow.com/questions/47333733/cakephp3-load-plugin-for-special-prefix
