### ISSUE TITLE
Documentation for columns doesn't work

### ISSUE THREAD

**Issue by curtisgibby** [Holt59/cakephp3-bootstrap-helpers#146]
The [horizontal form docs page](https://holt59.github.io/cakephp3-bootstrap-helpers/form-helper/horizontal/) includes the following snippet that doesn't work.

```php
echo $this->Form->setConfig('columns', [ // Total is 12, default is 2 / 10 / 0
    'label' => 2,
    'input' => 10,
    'error' => 0 // 0 for 'error' means that it will be put under the input
]);
```

I'm pretty sure this doesn't currently work, and that the config should be the following:

```php
echo $this->Form->setConfig('columns', [
        'md' => [ // Total is 12, default is 2 / 10 / 0
            'label' => 2,
            'input' => 10,
            'error' => 0 // 0 for 'error' means that it will be put under the input
        ]
    ]
);
```

**Comment by Holt59** [comment]
You're right, this is an artefact from an old version, I have removed this part and simply keep the next section (with `md` and `sm`).
