### ISSUE TITLE
Add Modal Size Option Example

### ISSUE THREAD

**Issue by stosh15x** [Holt59/cakephp3-bootstrap-helpers#154]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] question

* CakePHP Version: 3.6.

Can we add a modal "size" option example to this page? https://holt59.github.io/cakephp3-bootstrap-helpers/modal-helper/basics/

I had to dig through past bugs to figure this one out...

**Comment by Holt59** [comment]
This feature is documented in the API documentation: https://holt59.github.io/cakephp3-bootstrap-helpers/api/class-Bootstrap.View.Helper.ModalHelper.html#_create

There are too many options for me to create an example on the main documentation for each one, but if you want to enhance the documentation yourself, feel free to submit a PR to the `mkdocs` branch.
