### ISSUE TITLE
Multiple controls at same row

### ISSUE THREAD

**Issue by vicmosin** [Holt59/cakephp3-bootstrap-helpers#164]
* [ ] bug
* [x] enhancement
* [x] question

* CakePHP Version: 3.6.
* Plugin Version/Branch: dev-4.0.1-alpha.

Any chance to implement multiple controls within same row at forms (similar to https://getbootstrap.com/docs/4.1/components/forms/#form-row) with current version?

**Comment by Holt59** [comment]
This is similar to #70 (old one... ) but with Bootstrap 4. I am currently lacking time to implement new features, but a quick workaround would be to alter the correct template:

```php
// Update the inputContainer template.
$this->Form->setTemplate('inputContainer', '<div class="form-group col-md-6 {{type}}{{required}}">{{content}}</div>');

// Open the form-row div manually.
echo '<div class="form-row">';

// Output your controls:
echo $this->Form->control(...);
echo $this->Form->control(...);

echo '</div>';

// Reset the template
$this->Form->setTemplate('inputContainer', '<div class="form-group {{type}}{{required}}">{{content}}</div>');
