### ISSUE TITLE
Packagist Sync Fails

### ISSUE THREAD

**Issue by alphp** [Holt59/cakephp3-bootstrap-helpers#171]
> Note: [GitHub Services are being deprecated](https://developer.github.com/changes/2018-04-25-github-services-deprecation/). Please contact your integrator for more information on how to migrate or replace a service with [webhooks](https://developer.github.com/webhooks/) or GitHub Apps.

![image](https://user-images.githubusercontent.com/8992091/51029598-1b133780-1597-11e9-9627-f0ec246717ac.png)

![image](https://user-images.githubusercontent.com/8992091/51029496-c53e8f80-1596-11e9-8609-95194e6f0bbb.png)
https://packagist.org/about#how-to-update-packages

**Comment by Holt59** [comment]
Thanks for pointing that out, this should be fixed now (I've reconfigured packagist).

**Comment by alphp** [comment]
Sync is now OK.
