### ISSUE TITLE
FormHelper :: control() should not default to FALSE values

### ISSUE THREAD

**Issue by starlocke** [Holt59/cakephp3-bootstrap-helpers#181]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] question

* CakePHP Version: 3.8
* Plugin Version/Branch: dev-master

### A bug was found

- Vanilla CakePHP 3.8 installed.
- Vanilla "tutorial" demo tables created.
- "cake bake all articles"
- Hey, the "required" decorators work just fine.

In contrast:

- A project migrated from CakePHP 3.4 -> 3.7, and even 3.8 suddenly lost the "required" decorators (asterisk, bold).

### A root cause was found and patch created

... See pull request.

**Comment by Holt59** [comment]
Closed by #182
