### ISSUE TITLE
Could you publish a new version (on packagist)?

### ISSUE THREAD

**Issue by davalb** [Holt59/cakephp3-bootstrap-helpers#185]
I would like to use your library in a cakephp 3.7 project. Unfortunately your library in version 3.1.1 is only compatible with cakephp <=3.5. This seems to have been fixed for quite some time in the master, so a new version would be great.

I know that I could ask composer to get the current master version of this library, but I don't want to do that with my app which is in production.

**Comment by Holt59** [comment]
Are you using Bootstrap 3 or Bootstrap 4?

**Comment by davalb** [comment]
Honestly, I am not using bootstrap at all. I am just using your UrlComparerTrait in my project (couldnt find another library which does the same thing)

**Comment by Holt59** [comment]
I've released a new version `v3.1.4` which should work with CakePHP 3.7 and 3.8.

**Comment by davalb** [comment]
thank you!
