### ISSUE TITLE
CakePHP 3.6 support

### ISSUE THREAD

**Issue by SyrixJumpa** [Holt59/cakephp3-bootstrap-helpers#186]
* [x] bug
* [ ] enhancement
* [x] question

* CakePHP Version: 3.6.15.
* Plugin Version/Branch: 3.1.4, dev-master.

### What you did
composer update during deployment.

### What happened
The current library verssion does not seem to support CakePHP 3.6.* anymore, neither does the previous version (3.1.2) nor the version 4.0.1-alpha. Is there a release version we can use?

### What you expected to happen
CakePHP 3.6.* support.

**Comment by k-risc** [comment]
Same here, this is currently blocking prod deployments as well as rendering the development environment unusable. composer was set up to use "dev-master", and after the latest change in dev-master, with the resulting set of releases of cakephp3-bootstrap-helpers that is now available, CakePHP version 3.6.x does not seem to be supported.

**Comment by Holt59** [comment]
Sorry for the inconvenience, [3.1.3](https://github.com/Holt59/cakephp3-bootstrap-helpers/tree/v3.1.3) has been updated to target CakePHP 3.6.

**Comment by SyrixJumpa** [comment]
Tag 3.1.3 is working with CakePHP 3.6, thank you.
