### ISSUE TITLE
I did follow but failed

### ISSUE THREAD

**Issue by vothanhphat** [Holt59/cakephp3-bootstrap-helpers#49]
I did follow but failed, you can mail your source for Bootstrapping CakePHP Helpers 3.x succeeded. Mail your vothanhphat@gmail.com.

Thank you! Looking forward to help !!

**Comment by Holt59** [comment]
Hi,

I am sorry but I did not understand what you failed at? If you want help installing the helpers, please explain what you have tried so far so that I can correct you.

Mikael

**Comment by vothanhphat** [comment]
Hi,



I've followed your instructions but the results are not correct.









Result :


​



Thank you! Looking forward to help !!



2015-08-30 22:50 GMT+07:00 Mikaël Capelle <notifications@github.com>:

> Hi,
>
> I am sorry but I did not understand what you failed at? If you want help
> installing the helpers, please explain what you have tried so far so that I
> can correct you.
>
> Mikael
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Holt59/cakephp3-bootstrap-helpers/issues/49#issuecomment-136155289>
> .
>



-- 
Vo Thanh Phat
Tel   : 0935487018 - 0962913547
Add : Hoa Tien, Hoa Vang, Da Nang

**Comment by Holt59** [comment]
You probably forget to include bootstrap css and js files into your project. The helpers does not include these files.
