### ISSUE TITLE
Trait error

### ISSUE THREAD

**Issue by Dualfaces** [Holt59/cakephp3-bootstrap-helpers#55]
When i update bootstrap3 plugin and edit names from Bootstrap3 to Bootstrap. I got this error. 

Error: Trait 'Bootstrap3\View\Helper\BootstrapTrait' not found 
File pathToProject\vendor\holt59\cakephp3-bootstrap3-helpers\src\View\Helper\BootstrapHtmlHelper.php 
Line: 29

But BootstrapTrait is in same  namespace, i do see reason for not working. (Sorry for my english)

**Comment by Holt59** [comment]
The plugin path seems incorrect (`bootstrap3` instead of `bootstrap`). If you are using `composer`, could you try completely removing the plugin and reinstalling it?

```
composer remove holt59/cakephp3-bootstrap3-helpers
composer require holt59/cakephp3-bootstrap-helpers:~3.0
```

**Comment by Dualfaces** [comment]
Yeah,  now its working. Thank you very much. :)
