### ISSUE TITLE
Request is being black holed when using useCustomFileInput => true

### ISSUE THREAD

**Issue by Tomicapo** [Holt59/cakephp3-bootstrap-helpers#56]
Hi, I noticed that when I enabled useCustomFileInput my request started being black holed.

The only way I found to get over this issue was to change the plugin as follows:

File: BootstrapFormHelper.php
Line: 447

Code before: 
```
    $options += ['secure' => true];
```

Code after: 
```
    $options += ['secure' => false];
```

I don't have time to investigate further. So, at least, I think it would be great if this setting is taken from the $options set when using the helper.

Example: 
```
    $this->Form->input('image', ['type' => 'file', 'secure' => false]);
```

Any thoughts?

**Comment by Holt59** [comment]
Hi,

I don't have any issue on my side... What do you mean by "my request started being black holed"? You weren't able to upload any file?

If so could you check the content of the hidden `file` input in javascript after having selected a file using the custom file input?

Can you also tell me what browser you are using and on what kind of server your application is hosted?

Thanks,

Mikael

**Comment by Tomicapo** [comment]
Hey! Thanks for the fast response!
I'm using latest CakePHP on a windows Xampp server (updated about a month ago), Google Chrome (latest) and my application has many things on it, so I'm not discarding some kind of conflict on my own app. But, I'm quite sure it isn't.

I think this "Black Hole" is a Security Component thing (from cake core). 
There's some kind of validation being run that fails if this "security" parameter is set to true.

__Html with 'useCustomFileInput' => true__
```html
<div class="form-group file">
    <label class="col-xs-7 col-sm-4 col-md-3 col-lg-3 control-label " for="users-cars-0-main-image">Foto De Tu Auto</label>
    <div class="col-xs-12 col-sm-6 col-md-7 col-lg-7">
        <input type="file" name="Users[cars][0][main_image]" id="users-cars-0-main-image" style="display: none;" onchange="document.getElementById('users-cars-0-main-image-input').value = (this.files.length <= 1) ? this.files[0].name : this.files.length + ' ' + 'files selected';">
        <div class="input-group">
            <div class="input-group-btn">
                <button type="button" onclick="document.getElementById('users-cars-0-main-image').click();" class="btn btn-default">Choose File</button>
            </div>
            <input type="text" name="Users[cars][0][main_image]" class="form-control " id="users-cars-0-main-image-input" readonly="readonly" onclick="document.getElementById('users-cars-0-main-image').click();">
        </div>
    </div>
</div>
```

__Html with 'useCustomFileInput' => false__
```html
<div class="form-group file">
    <label class="col-xs-7 col-sm-4 col-md-3 col-lg-3 control-label " for="users-cars-0-main-image">Foto De Tu Auto</label>
    <div class="col-xs-12 col-sm-6 col-md-7 col-lg-7">
        <input type="file" name="Users[cars][0][main_image]" id="users-cars-0-main-image">
    </div>
</div>
```




__Complete form:__
```html
<form method="post" accept-charset="utf-8" role="form" action="/mi-perfil">
    <div style="display:none;">
        <input type="hidden" name="_method" class="form-control " value="PUT">
    </div>
    <div class="form-group file">
        <label class=" control-label " for="users-cars-0-main-image">Foto De Tu Auto</label>
        <input type="file" name="Users[cars][0][main_image]" id="users-cars-0-main-image" style="display: none;" onchange="document.getElementById('users-cars-0-main-image-input').value = (this.files.length <= 1) ? this.files[0].name : this.files.length + ' ' + 'files selected';">
        <div class="input-group">
            <div class="input-group-btn">
                <button type="button" onclick="document.getElementById('users-cars-0-main-image').click();" class="btn btn-default">Choose File</button>
            </div>
            <input type="text" name="Users[cars][0][main_image]" class="form-control " id="users-cars-0-main-image-input" readonly="readonly" onclick="document.getElementById('users-cars-0-main-image').click();">
        </div>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary btn btn-default" id="editProfileSubmitBtn" value="Actualizar Perfil">
    </div>
    <div style="display:none;">
        <input type="hidden" name="_Token[fields]" class="form-control " value="3d38c09a63d860cfd67c18c4d49aea505b91a01b%3A">
        <input type="hidden" name="_Token[unlocked]" class="form-control " value="">
    </div>
</form>
```

**Comment by Holt59** [comment]
I now this is old but maybe this pull request fixes the problem? https://github.com/Holt59/cakephp3-bootstrap-helpers/pull/80

**Comment by Holt59** [comment]
I am closing this, feel free to reopen it (or a new issue) if this is not solved.

**Comment by ypnos-web** [comment]
Hello,

unfortunately now I get the same(?) error:

> Unexpected field 'filename-text' in POST data, Unexpected field 'filename.error' in POST data, Unexpected field 'filename.name' in POST data, Unexpected field 'filename.size' in POST data, Unexpected field 'filename.tmp_name' in POST data, Unexpected field 'filename.type' in POST data, Missing field 'filename' in POST data
Cake\Controller\Exception\AuthSecurityException

See https://book.cakephp.org/3.0/en/controllers/components/security.html#form-tampering-prevention

I did not have this problem with Cake 3.3.X, I see it since migrating to 3.4.X.

**Comment by Holt59** [comment]
I am not sure this is related to the original issue of this thread... Could you open a new one and add a `debug` of `$data`  before the form?
