### ISSUE TITLE
Flash Helper Error

### ISSUE THREAD

**Issue by stillfire** [Holt59/cakephp3-bootstrap-helpers#59]
Hey, I have added this to my AppController.php

```
public $helpers = [
        'Html' => [
            'className' => 'Bootstrap.BootstrapHtml'
        ],
        'Form' => [
            'className' => 'Bootstrap.BootstrapForm',
            'useCustomFileInput' => true
        ],
        'Paginator' => [
            'className' => 'Bootstrap.BootstrapPaginator'
        ],
        'Modal' => [
            'className' => 'Bootstrap.BootstrapModal'
        ],
        'Flash' => [
            'className' => 'Bootstrap.BootstrapFlash'
        ]
    ];
```

I am getting an error whenever the flash is supposed to be displayed.

```
Element/.ctp 

Cake\View\Exception\MissingElementException
```

Does the helper automatically apply to

``` 
$this->Flash->error(__('The tag could not be saved. Please, try again.'));
```

Or did I miss a step?

Thanks,

**Comment by Holt59** [comment]
There was a bug with the new namespace name, could try updating (using the `dev-master` branch) and tell me if it works now?

**Comment by stillfire** [comment]
Thanks for getting back to me! I did the update but I am still getting the same error.

    Element/.ctp 

    Cake\View\Exception\MissingElementException

    ⟩ Cake\View\View->element ROOT/vendor/holt59/cakephp3-bootstrap-helpers/src/View/Helper/BootstrapFlashHelper.php, line 92

    line 92: return $this->_View->element($flash['element'], $flash); 

Am I missing anymore code additions, or do I simply need to add the Flash helper to the AppController.php

Thanks.

**Comment by Holt59** [comment]
Do you still have the problem since commit 8083a65e3971350db5b793c5ff343e51b1598857?

**Comment by stillfire** [comment]
Awesome! It is working now!! Thank you!
