### ISSUE TITLE
Validation : Array to string conversion in CakePHP 3.1.4

### ISSUE THREAD

**Issue by n0mad01** [Holt59/cakephp3-bootstrap-helpers#62]
i get this notice in the most recent CakePHP version 3.1.4 but no Validation message:

Notice (8): Array to string conversion [ROOT\vendor\holt59\cakephp3-bootstrap-helpers\src\View\BootstrapStringTemplate.php, line 70]

best regards

**Comment by Holt59** [comment]
Could you show me with which code you get the following message? I don't get it using CakePHP 3.1.4 and the latest version of the helpers.

**Comment by n0mad01** [comment]
Thanx for the quick response!
This happens when i use a Custom Validation rule:

View:
`echo $this->Form->input( 'company.name', [
    'label' => _('name'),
]);`

Controller:
`$user = $this->Users->patchEntity(
    $user,
    $this->request->data,
    [
        'validate' => 'CUSTOM1',
        'associated' => [
            'Companies' => [
                'validate' => 'CUSTOM2',
            ],
        ]
    ]
);`

**Comment by Holt59** [comment]
I've just checked CakePHP official repo. and it looks like they made a change to the `StringTemplate` class in [this commit](https://github.com/cakephp/cakephp/commit/5f5d1e19dbacdb95de523aade4835a6325b15e6c). I have reflected the change to my `BootstrapStringTemplate` in c1efda00bdd750cdc5b30db0a527d9b71bc7bdbc, I hope this will be enough, please let me know.

**Comment by n0mad01** [comment]
wow, great, thanx!
