### ISSUE TITLE
Form buttons with icons not possible

### ISSUE THREAD

**Issue by ypnos** [Holt59/cakephp3-bootstrap-helpers#63]
This does not work as intended:

````php
<?= $this->Form->submit($this->Html->icon('check').' '.__('Save'),
        ['bootstrap-type' => 'primary', 'escape' => 'false']) ?>
````

The `escape` option is ignored so the HTML rendered by `icon()` is escaped.

In general an `icon` option for buttons might be nice as well. I assume it is a common use-case.

**Comment by Holt59** [comment]
This is not related to the helpers. If you use the `submit` method of cakephp, what you get is something like (it is not a `button` tag!):
```html
<input type="submit" value="Your caption" />
```
You cannot add HTMl in the `value` attribute of an input, so you must something else. This should work:
```php
<?= $this->Form->button($this->Html->icon('check').' '.__('Save'),
        ['type' => 'submit', 'bootstrap-type' => 'primary', 'escape' => 'false']); ?>
```

**Comment by ypnos** [comment]
I'm sorry while I did use `submit()` in my example I also tried `button()` to no avail.
Your example produces this output:
````html
<button type="submit" class="btn btn-primary">&lt;i class=&quot;fa fa-check&quot;&gt;&lt;/i&gt; Save</button>
````

**Comment by Holt59** [comment]
In your example, you also put `'false'` instead of `false` (which I unfortunately copied in my answer... ). It is a copy/paste mistake?

**Comment by ypnos** [comment]
Yes this is a weird mistake, sorry for stealing your time!

In a related note, _getColClass() is protected so it seems hard to align the custom submit button correctly in a "clean" fashion the same way as submit() produces an aligned button.

**Comment by Holt59** [comment]
You could try something like that (not tested):
```php
<?= $this->Form->formatTemplate('submitContainer', [
    'content' => $this->Form->button (...)
]) ; ?>
```
Making the `_getColClass` public would not help anyway because it is the whole `submitContainer` wrapping that you want to reproduce.

**Comment by ypnos** [comment]
This is what I searched for, it is extremely helpful. Now I also understand better the inner workings and how to operate with your form helper. Thank you very much!
