### ISSUE TITLE
Checkbox / Radio with Javascript

### ISSUE THREAD

**Issue by rifton007** [Holt59/cakephp3-bootstrap-helpers#64]
Hi all, thanks for your help.

How to create a radio group, as in the link below.
http://getbootstrap.com/javascript/#buttons-checkbox-radio.

I'm on CakePHP 2.x and I do not know how?
And thank you for your plugin.

**Comment by Holt59** [comment]
Hi,

If you are using CakePHP 2.x, please post this issue in the corresponding repository: https://github.com/Holt59/cakephp-bootstrap3-helpers

Thanks,
