### ISSUE TITLE
Radio button

### ISSUE THREAD

**Issue by caBBAlainB** [Holt59/cakephp3-bootstrap-helpers#65]
Hello,
It seems we talk about this feature already and I think you told me this functionality should be available in the last versions but I didn't see it in your wiki page.
I tried using the cakePHP3 helper method but I cannot get it working.
Is it normal?
Is there a way to use it with your module?

The ctp code I use is:
```php
<?= $this->Form->radio(
     'agpoiaudios.'.$ntext.'.rec_mod',
     [
          ['value' => 'sv', 'text' => __('Synthèse vocale')],
          ['value' => 'vh', 'text' => __('voix humaine (sur devis)')],
     ]
 ); ?>
```
The generated html code is:
```html
<div class="radio">
	<label for="agpoiaudios-0-rec-mod-sv">
		<input type="radio" name="agpoiaudios[0][rec_mod]" value="sv" id="agpoiaudios-0-rec-mod-sv">Synthèse vocale
	</label>
</div>
<div class="radio">
	<label for="agpoiaudios-0-rec-mod-vh">
		<input type="radio" name="agpoiaudios[0][rec_mod]" value="vh" id="agpoiaudios-0-rec-mod-vh">voix humaine (sur devis)
	</label>
</div>
```
Do you see any reason why it doesn't work?

regards,
Alain

**Comment by Holt59** [comment]
You need to use the `input` method if you want bootstrap wrapping, the specific method (`radio`, `checkbox`, etc. will only give you raw inputs). Try:
```php
<?= $this->Form->input(
    'agpoiaudios.'.$ntext.'.rec_mod',
    [
        'type' => 'radio',
        'options' => 
        [
            ['value' => 'sv', 'text' => __('Synthèse vocale')],
            ['value' => 'vh', 'text' => __('voix humaine (sur devis)')],
        ]
    ]
); ?>
```

**Comment by caBBAlainB** [comment]
ah ok, thanks.
but I think the example is not in the form helper examples. https://holt59.github.io/cakephp3-bootstrap-helpers/
Maybe you could add it.
Thanks anyway.

**Comment by caBBAlainB** [comment]
I tried to modify the input according to your advice.
I doesn't work more but maybe there is a problem with the syntax.
The generated code is:

    <label class=" control-label " >Rec Mod</label>
    <input type="hidden" name="agpoiaudios[0][rec_mod]" class="form-control "  value="" />
	<div class="radio">
		<label for="agpoiaudios-0-rec-mod-sv">
			<input type="radio" name="agpoiaudios[0][rec_mod]" value="sv" id="agpoiaudios-0-rec-mod-sv">Synthèse vocale
		</label>
	</div>
	<div class="radio">
		<label for="agpoiaudios-0-rec-mod-vh">
			<input type="radio" name="agpoiaudios[0][rec_mod]" value="vh" id="agpoiaudios-0-rec-mod-vh">voix humaine (sur devis)
		</label>
	</div>
    </div>

And if you look at it carefully, the tag `<input type="radio"...` is not closed.
Is it normal?
verified in source code in Firefox and Chromium

**Comment by Holt59** [comment]
The output is correct, see [http://getbootstrap.com/css/#checkboxes-and-radios](bootstrap official documentation). What output do you expect?

**Comment by caBBAlainB** [comment]
Your are right, I didn't pay attention that the text is the label and the tag is correctly closed just before.
Anyway, I cannot activate any radio button and I don't understand why...
Maybe I could have a problem with another helper. I check.

**Comment by Holt59** [comment]
Which browser are you using? Maybe it is because you have a  `hidden` input with the same name...

**Comment by caBBAlainB** [comment]
I tried on Firefox and chromium. same problem.
But I just tried without your helper and also same problem!?!

**Comment by Holt59** [comment]
To check the a default value in a set of radio button, you need to passe a `value` option I think, see [the official CakePHP doc](http://book.cakephp.org/3.0/en/views/helpers/form.html#creating-radio-buttons) (all options you send to the `input` method is send to the `radio` method).

**Comment by 2ndGAB** [comment]
I looked at the CakePHP doc but didn't really see how to deal with the input() parameters compared to radio() method.
AFAIR, I tried maybe `['value' => 'vh']` and maybe not `'value' => 'vh'`; I'll check tomorrow. Anyway, in the hidden input, I see `'value' = ''`

**Comment by Holt59** [comment]
I can't help you more, the following work as expected on my machine:
```php
echo $this->Form->input(
    'agpoiaudios.xxx.rec_mod', [
        'type' => 'radio',
        'options' => [
            ['value' => 'sv', 'text' => __('Synthèse vocale')],
            ['value' => 'vh', 'text' => __('voix humaine (sur devis)')],
        ],
        'value' => 'vh'
    ]
);
```
Output:
```html
<label class=" control-label ">Rec Mod</label>
<input name="agpoiaudios[xxx][rec_mod]" class="form-control " value="" type="hidden">
<div class="radio">
    <label for="agpoiaudios-xxx-rec-mod-sv">
        <input name="agpoiaudios[xxx][rec_mod]" value="sv" id="agpoiaudios-xxx-rec-mod-sv" type="radio">Synthèse vocale
    </label>
</div>
<div class="radio">
    <label for="agpoiaudios-xxx-rec-mod-vh">
        <input name="agpoiaudios[xxx][rec_mod]" value="vh" id="agpoiaudios-xxx-rec-mod-vh" checked="checked" type="radio">voix humaine (sur devis)
    </label>
</div>
```

**Comment by 2ndGAB** [comment]
I appreciate your help, Mickael, unfortunately I don't have much time currently to work on it, but I' will certainly find what's wrong with yuour advices.
Thanks a lot.

**Comment by 2ndGAB** [comment]
So, just to give news about this problem after I had time to analyse it a bit more.
I found what caused the problem in my case and found a workaround but it remains understandable.
What I can say is that the problem is caused by a button. Oh sure not exactly by it because if I copy/paste the whole page in jsFiddle, using the external resources I use, everything is ok so...

But I have the problem in all browsers and if the code (excerpt) is this one:

	<button type="button" class="btn btn-danger reset_file" id="reset_file-<?=$ntext?>"><?=__("Supprimer le fichier audio")?></button>

	<div class="col-md-12 col-md-offset-1">
		<?= $this->FormH->input(
		    'agpoiaudios.'.$ntext.'.rec_mod',
		    [
		        'type' => 'radio',
	    		'label' => false,
	    		'options' => 
		        [
		            ['value' => 'sv', 'text' => __('Synthèse vocale')],
		            ['value' => 'vh', 'text' => __('voix humaine (sur devis)')],
		        ],
				'default' => 'sv'
		    ]
		); ?>
	</div>

Now, if I simply invert button and radios, the problem desappear.

	<div class="col-md-12 col-md-offset-1">
		<?= $this->FormH->input(
		    'agpoiaudios.'.$ntext.'.rec_mod',
		    [
		        'type' => 'radio',
	    		'label' => false,
	    		'options' => 
		        [
		            ['value' => 'sv', 'text' => __('Synthèse vocale')],
		            ['value' => 'vh', 'text' => __('voix humaine (sur devis)')],
		        ],
				'default' => 'sv'
		    ]
		); ?>
	</div>

	<button type="button" class="btn btn-danger reset_file" id="reset_file-<?=$ntext?>"><?=__("Supprimer le fichier audio")?></button>


Sorry, that's not what we can call a solution, that doesn't explain anything but just gives idea, maybe, and a workaround to anybody who could face a so bizarre thing!

**Comment by Holt59** [comment]
Could you remind what exactly is the issue here because I don't see the link with your original post? Could you also post a screen shot of the actual and expected output?

**Comment by 2ndGAB** [comment]
Radio button where simply not selectable.

html ouput was perfectly correct and radios were visually perfect but impossible to select any of them, just as if they were simple texts.
So I don't see what I can say more as there is nothing to tell unfortunately.

As I said, copy/paste my page in jsFiddle perfectly works but it's diffcult to be in the exact same conditions. I use jquery, bootstrap for whose I can add it via cdn, but I also use embedded css/js scripts and maybe the problem could come from one of them but anyway, the problem looks very strange.

**Comment by Holt59** [comment]
If it works in a fiddle,  you probably have an element hover your radio which is only present if the button is before the radio elements... Check in your developer console to see if there is anything like that.

**Comment by 2ndGAB** [comment]
Maybe something like that yes. I'm going to see more precisely such thing.
Thanks
