### ISSUE TITLE
Duplicated attribute class when adding custom classes

### ISSUE THREAD

**Issue by L1lle** [Holt59/cakephp3-bootstrap-helpers#69]
Hi,

When adding a custom class to an input the attribute `class` is added twice.

```
$this->Form->input('name',array('class'=>'input-lg'))
````

Returns the following

````
<div class="form-group text">
	<label class="control-label "  for="name">Name</label>
	<input type="text" name="name" class="form-control input-lg"  class="input-lg" id="name" />
</div>
`````

The attribute __class__ exists two times. Most browser don't care about it, but it's not W3C valid and a bit  confusing.

**Comment by Holt59** [comment]
Should be corrected by https://github.com/Holt59/cakephp3-bootstrap-helpers/commit/3177b84d56df5a9ef87f427a098a83b2fc3b9ad3, I thought I had made this change months ago but apparently I did not push it...

**Comment by L1lle** [comment]
works great. thanks for the quick fix.
