### ISSUE TITLE
Allow overwriting the id of a search form

### ISSUE THREAD

**Issue by nrother** [Holt59/cakephp3-bootstrap-helpers#71]
Current the input in a search form created with `FormHelper::searchForm` has always the default id of `search`. It would be nice if one could change that, e.g. if you want to have more than one form on the same page.

**Comment by Holt59** [comment]
See commit https://github.com/Holt59/cakephp3-bootstrap-helpers/commit/6e24f6bd9a0ce0696708b6937f1b092284e4eff8.

**Comment by nrother** [comment]
Great, this solves the problem (and even a lot more :grinning: )
