### ISSUE TITLE
Enhance easy icon to be used alongside text

### ISSUE THREAD

**Issue by ypnos-web** [Holt59/cakephp3-bootstrap-helpers#72]
Right now we can either have a button with text **or** an icon. But having both is also a very common use-case.

See the examples under "Bootstrap 3 Examples" at https://fortawesome.github.io/Font-Awesome/examples/

It would be great if one could set a title like `i:plus Create` and get a button with a plus icon and "Create".

**Comment by Holt59** [comment]
Should work with commit https://github.com/Holt59/cakephp3-bootstrap-helpers/commit/23e809bd7f00f72831111a8334c3414bafcff634, but only with icon at the beginning / the end (not in the middle).

**Comment by ypnos-web** [comment]
Looks pretty awesome to me!

**Comment by Holt59** [comment]
I am closing this issue, Feel free to reopen it if something goes wrong with the update!
