### ISSUE TITLE
_groupTemplate() misses templateVars support

### ISSUE THREAD

**Issue by ypnos-web** [Holt59/cakephp3-bootstrap-helpers#73]
The support for `templateVars` option was added in CakePHP 3.1.0. In the `FormHelper` you can find it here:
https://github.com/cakephp/cakephp/blob/928beba6f76c6d1e884ae26f42c86a25717a1a85/src/View/Helper/FormHelper.php#L1063

However, BootstrapFormHelper overrides this function. The line in question that adds templateVars to the array is notably missing here:
https://github.com/Holt59/cakephp3-bootstrap-helpers/blob/950221c851dc22da89a8d85820194c89296f6670/src/View/Helper/BootstrapFormHelper.php#L403

Therefore, this does not work: http://book.cakephp.org/3.0/en/views/helpers/form.html#adding-additional-template-variables-to-templates

I can confirm that it does work correctly after adding FormHelper.php#L1063 before BootstrapFormHelper.php#L40.

**Comment by Holt59** [comment]
Thanks for the feedback, I don't think that override is relevant since the addition of `templateVars`, I will push a fix as soon as I can.

**Comment by ypnos-web** [comment]
So you will use templateVars for the _data stuff? I didn't even think about it..
If you give me a hint on the template <-> templateVars matching of _data I can also help out and do a pull request that does that.

**Comment by Holt59** [comment]
Basically, the `$options['_data'] = ...` in the `input` methods should be replaced by `$options['templateVars'] += ...` and `$options += ['templateVars' => []]` should be added at the beginning of the method. And the `_groupTemplate` method should be deleted.

**Comment by Holt59** [comment]
I have created a branch with a fix, but I will not merge it as long as I have not tested it (can't test it right now I don't have a PHP environment installed here).

**Comment by ypnos-web** [comment]
I tested your fix. Unfortunately it destroys horizontal forms, as `FormHelper::_groupTemplate` does not call `self::formatTemplate()`. Instead it calls `$this->templater()->format()` directly, so this injection does not happen anymore:

```php
    return $this->templater()->format($name, $this->_getDefaultTemplateVars($data));
```

I don't know what is most appropriate to address this.

**Comment by Holt59** [comment]
Thanks for testing the *fix*, I think the easiest way is to override `_groupTemplate`, but only to replace `$this->templater()->format` by `$this->formatTemplate`. You can try adding the following to `BootstrapFormHelper`:

```php
/**
 * Generates an group template element
 *
 * @param array $options The options for group template
 * @return string The generated group template
 */
protected function _groupTemplate($options)
{
    $groupTemplate = $options['options']['type'] . 'FormGroup';
    if (!$this->templater()->get($groupTemplate)) {
        $groupTemplate = 'formGroup';
    }
    return $this->formatTemplate($groupTemplate, [
        'input' => $options['input'],
        'label' => $options['label'],
        'error' => $options['error'],
        'templateVars' => isset($options['options']['templateVars']) ? $options['options']['templateVars'] : []
    ]);
}
```

**Comment by ypnos-web** [comment]
Yes, I also submitted a pull request to cakephp: https://github.com/cakephp/cakephp/pull/8280

**Comment by Holt59** [comment]
Great idea, I'll probably make a fix for CakePHP < 3.2.3 and tag it with a new version and then update the plugin and `composer.json` to target CakePHP 3.2.3+.

**Comment by Holt59** [comment]
Should be fixed by now. I'll try to follow up on CakePHP when 3.2.3 get released.

**Comment by ypnos-web** [comment]
Great!

**Comment by Holt59** [comment]
Since CakePHP 3.2.3 has just been released, I have updated the master branch to match CakePHP 3.2.3 behaviour (I updated [`composer.json`](https://github.com/Holt59/cakephp3-bootstrap-helpers/blob/master/composer.json) to require CakePHP >= 3.2.3 and I removed the override of [`_groupTemplate`](https://github.com/Holt59/cakephp3-bootstrap-helpers/blob/master/src/View/Helper/BootstrapFormHelper.php#L395) in the FormHelper). 

I have create [a tag](https://github.com/Holt59/cakephp3-bootstrap-helpers/tree/v3.0.5) for older version in case people do not want to udpate their cakephp version.

I also added a [small test](https://github.com/Holt59/cakephp3-bootstrap-helpers/blob/master/tests/TestCase/View/Helper/BootstrapFormHelperTest.php#L563) for `templateVars` in `inputContainer`.
