### ISSUE TITLE
Icon in panel title

### ISSUE THREAD

**Issue by assisjeferson** [Holt59/cakephp3-bootstrap-helpers#77]
I like to use icon in panel title, like this:

![screen shot 2016-03-03 at 18 02 43](https://cloud.githubusercontent.com/assets/331113/13509453/405819c0-e16a-11e5-9f72-18e248335f3b.png)

But today dont have a option for this, I think a `$option` in `$this->Panel->create()` or in `$this->Panel->header()`

Is possible make a icon, concatenating icon with title

```php
$this->Panel->create($this->Html->icon('info').'&nbsp;&nbsp; This is the first panel');
```

_Sorry my bad english :(_

**Comment by Holt59** [comment]
The following:

```php
$this->Panel->create($this->Html->icon('info').'&nbsp;&nbsp; This is the first panel');
```

...works for me, did you try it?

**Comment by Holt59** [comment]
Starting with 594e627a6f561cc6884653fdf2bf195a72390a0d, you should be able to use `easyIcon` with Panel:

```php
echo $this->Panel->create('i:info This is the first panel!')
```

**Comment by assisjeferson** [comment]
Thanks Hol59, its work perfectly and my code stay more beautiful
