### ISSUE TITLE
Remove `BootstrapTrait::_extractType()`

### ISSUE THREAD

**Issue by ypnos-web** [Holt59/cakephp3-bootstrap-helpers#79]
I understand the idea of checking if a type argument is valid. However, if it is not, instead of silently ignoring the argument, arguably a `InvalidArgumentException` should be thrown.

I have a problem with this kind of error checking in general however: It is perfectly normal to add custom types. E.g. define
```css
.label-generic {
    background-color: #9b59b6;
}
```
Now, calling HTML->label('generic', 'generic') fails. But it need not to.

I suggest to get rid of this functionality altogether. If a type is provided, expect it to be fine and just go through with it.

**Comment by Holt59** [comment]
I [removed](https://github.com/Holt59/cakephp3-bootstrap-helpers/commit/2f1e84a7828f32b0ae7603a14f40fd4d51d46a8a) the `_extractType` method, it was an artefact of the old CakePHP 2 version of the plugin.

**Comment by Holt59** [comment]
I am closing this, not that you can now set default label type using (maybe it will simplify your work):

```php
$this->loadHelper('Html', [
    ...,
    'label.type' => 'generic'
]);
// Or...
$this->Html->config('label.type', 'generic');
```

Feel free to reopen if it does not solve your problem.
