### ISSUE TITLE
NavbarHelper::searchForm should set default alignment

### ISSUE THREAD

**Issue by nrother** [Holt59/cakephp3-bootstrap-helpers#81]
For a working search form in your navbar you have to add `['class' => 'navbar-left']` (or `navbar-right`) to the options, otherwise the rendering breaks. This is required by bootstrap, according to the [docs](http://getbootstrap.com/components/#navbar-forms).

`NavbarHelper::searchForm` should set a default alignment (probably `navbar-left`.)

**Comment by Holt59** [comment]
Should be fixed by https://github.com/Holt59/cakephp3-bootstrap-helpers/commit/159353ed2ca3b2e411e040fc7d5cbe804a192426.

**Comment by nrother** [comment]
Wow, 3 minutes and the bug is fixed! :tada: 
It works now out-of-box.
