### ISSUE TITLE
Inconsistent licensing.

### ISSUE THREAD

**Issue by ADmad** [Holt59/cakephp3-bootstrap-helpers#84]
Your readme says the code is MIT licensed but individual files (BootstrapHtmlHelper for e.g.) states it's under Apache v2 license. It would be nice for users if the code uses a single license consistently.

**Comment by Holt59** [comment]
Thanks for pointing this out, I switched to MIT license a few times ago and forgot to update the individual files. I have corrected that with commit 1c7e8ba651bda8cc00554ba1242e71d026f1e3a0, everything should now be licensed under MIT license.
