### ISSUE TITLE
Correção na documentação

### ISSUE THREAD

**Issue by Eduardoavargas** [Holt59/cakephp3-bootstrap-helpers#85]
Em seu site (https://holt59.github.io/cakephp3-bootstrap-helpers/#helpers-form) você ensina a especificar os tamanhos com "columns" 

>   [`<?php`](https://holt59.github.io/cakephp3-bootstrap-helpers/#helpers-form)

    echo $this->Form->create(null, [
        'horizontal' => true,
        'columns' => [ 
            'sm' => [
                'label' => 4,
                'input' => 4,
                'error' => 4
            ],
            'md' => [
                'label' => 2,
                'input' => 6,
                'error' => 4
            ]
        ]
    ]);

Porem só consegui alterando para "cols"

> <?php

    echo $this->Form->create(null, [
        'horizontal' => true,
        'cols' => [ 
            'sm' => [
                'label' => 4,
                'input' => 4,
                'error' => 4
            ],
            'md' => [
                'label' => 2,
                'input' => 6,
                'error' => 4
            ]
        ]
    ]);

**Comment by Holt59** [comment]
If you can only change the size using `"cols"`, it means you have an old version of the plugin. You need to require the `dev-master` branch when installing the plugin:

    composer require holt59/cakephp3-bootstrap-helpers:dev-master

Otherwise you will get an outdated version.
