### ISSUE TITLE
Add support for checkbox "required"

### ISSUE THREAD

**Issue by zschwinges** [Holt59/cakephp3-bootstrap-helpers#88]
Please add {{required}} to the checkbox class.

Replace in BootstrapFormHelper: 

`'checkboxContainer' => '{{h_checkboxContainer_start}}<div class="checkbox">{{content}}</div>{{h_checkboxContainer_end}}',
`

with

`'checkboxContainer' => '{{h_checkboxContainer_start}}<div class="checkbox {{required}}">{{content}}</div>{{h_checkboxContainer_end}}',`

Thank You!

**Comment by Holt59** [comment]
This should be fixed by 07e00290af09a1a50ee8ba708357b9af56c56e14 (not tested).
