### ISSUE TITLE
Add support for Bootstrap Select List {{label}}

### ISSUE THREAD

**Issue by DrizztDarnok** [Holt59/cakephp3-bootstrap-helpers#90]
Hi,
I would like to add a Label to a select list.

Thank You! # #

**Comment by Holt59** [comment]
Hi,

Could you elaborate on what you want to do?

Thanks,

M.

**Comment by DrizztDarnok** [comment]
Hi,
I'm creating a kind of survey and making the profils editable. 
For that I want to give options, with a select list.
For example selecting a gender:
'<div class="form-group">

    <label for="gender" class="col-md-4 control-label" ><?=__('Gender')?></label>
    <div class="col-md-4">
        <?php                         
            echo $this->Form->select('gender', $options_gender);
        ?>
    </div>   
</div>'
  
Currently im making this by hand. Because I didn't find an option to give labels to a select pickers...
I hope this helps..

Thanks for the great work sofar,
K

**Comment by Holt59** [comment]
Hi,

This plugins follows CakePHP standard - If you want a complete input (with `label`, layout, ...), you need to use the `input` method, not the `select` method (which is only designed to allow the output of a *raw* select).

In your case this would be:

```php
$this->Form->input('gender', $options_gender);
```
Or something alike...

If you want the label in a column and the input in another one, you need to use the horizontal versions, see [the documentation](https://holt59.github.io/cakephp3-bootstrap-helpers/#horizontal-forms).
