### ISSUE TITLE
Button support outside of forms

### ISSUE THREAD

**Issue by swimboy** [Holt59/cakephp3-bootstrap-helpers#91]
Any possibility that `$this->Html->button("Push Me", "success")` could be supported outside of a form? Or is it already and I'm just doing something wrong?

**Comment by Holt59** [comment]
It should work but the `button` method is in the `Form` helper:

```php
echo $this->Form->button('Push Me', ['bootstrap-type' => 'success']);
```

**Comment by swimboy** [comment]
Thanks! I just assumed that since it was part of the Form helper, that it would only work in forms.
