### ISSUE TITLE
Problem with input file in case of validation error

### ISSUE THREAD

**Issue by 2ndGAB** [Holt59/cakephp3-bootstrap-helpers#92]
Hello,

When I get an error message in a file input, this one is filled up by the object as shown below.

![file input field](http://i.imgur.com/Au6Yrli.png)

Here is the object content:

	'guide' => object(App\Model\Entity\Guide) {

		'card' => 'passpack_encrypted_export_2014_01_05T15_26.pp',
		'[new]' => true,
		'[accessible]' => [
			'site_id' => true,
			'card' => true,
			'fileCard' => true
		],
		'[dirty]' => [
			'card' => true
		],
		'[original]' => [],
		'[virtual]' => [],
		'[errors]' => [
			'fileCard' => [
				'file' => 'extensions autorisées: jpg, png, pdf'
			]
		],
		'[invalid]' => [
			'fileCard' => [
				'name' => 'passpack_encrypted_export_2014_01_05T15_26.pp',
				'type' => 'application/octet-stream',
				'tmp_name' => '/tmp/php6zxUDT',
				'error' => (int) 0,
				'size' => (int) 29766
			]
		],
		'[repository]' => 'Guides'

	},
How to prevent it?

**Comment by Holt59** [comment]
Hi, thanks for your feedback. This should be fixed by 76a417e5e995fb38e8ce739d4cdf8e2cc2fdc68e.

**Comment by 2ndGAB** [comment]
@Holt59 Perfect Mikaël, I'll try it.

**Comment by 2ndGAB** [comment]
I tried it and it works but maybe the problem is that you clear the input field so the use cannot see what he uploaded by mistake.

it's just a suggestion but maybe a better solution would be the following one:

    public function file($fieldName, array $options = []) {

        if (!$this->config('useCustomFileInput')
            || (isset($options['default']) && $options['default'])) {
            return parent::file($fieldName, $options);
        }

        $options += [
            '_input'  => [],
            '_button' => [],
            'id' => $fieldName,
            'secure' => true,
            'count-label' => __('files selected'),
            'button-label' => __('Choose File')
        ];

        $fakeInputCustomOptions = $options['_input'];
        $fakeButtonCustomOptions = $options['_button'];
        unset($options['_input'], $options['_button']);

        $options += ['secure' => true];
        $options = $this->_initInputField($fieldName, $options);
        unset($options['type']);
	    
	    /*
	     * ndgAlainB
	     */
	    $fakeInputCustomOptions += [
	        'value' => $options['val']['name'] // fill in with previoulsy uploaded filename
	    ];

        $countLabel = $options['count-label'];
        unset($options['count-label']);
        $fileInput = $this->widget('file', array_merge($options, [
            'style' => 'display: none;',
            'onchange' => "document.getElementById('".$options['id']."-input').value = (this.files.length <= 1) ? this.files[0].name : this.files.length + ' ' + '" . $countLabel . "';"
        ]));

        $fakeInput = $this->text($fieldName, array_merge($fakeInputCustomOptions, [
            'name' => $fieldName.'-text',
            'readonly' => 'readonly',
            'id' => $options['id'].'-input',
            'onclick' => "document.getElementById('".$options['id']."').click();"
        ]));
        $buttonLabel = $options['button-label'];
        unset($options['button-label']);

        $fakeButton = $this->button($buttonLabel, array_merge($fakeButtonCustomOptions, [
            'type' => 'button',
            'onclick' => "document.getElementById('".$options['id']."').click();"
        ]));
        return $fileInput.$this->Html->div('input-group',
                                           $this->Html->div('input-group-btn',
                                                            $fakeButton).$fakeInput);
    }

But it's as you prefer of course.

**Comment by Holt59** [comment]
This should be updated with the latest commit (ad90cb82156ef38f9527df5421c1fad9cec4eb8d).

**Comment by 2ndGAB** [comment]
Thanks a lot

**Comment by Holt59** [comment]
I am closing this issue, feel free to open a new one if you have another problem with the custom file input!
