### ISSUE TITLE
Little problem with input file generated code

### ISSUE THREAD

**Issue by 2ndGAB** [Holt59/cakephp3-bootstrap-helpers#93]
Hi,

I have a little problem with the html code generated by the Form Helper for file input.
This is in a very specific case where I generate html code from javascript:

	function add_guide_card() {
		$("#guide_card").append(
			'<div class="col-md-8">\
				<?= $this->FormB->input('guide.fileCard', ['label' => __("Télécharger votre carte"), 'type' => 'file']); ?>\
			</div>');
	}

The generated code is: 

	<div class="form-group file">
		<label class="control-label col-md-2"  for="guide-filecard">Téléchager votre carte</label>
		<div class="col-md-10"><input type="file" name="guide[fileCard]"  id="guide-filecard" button-label="Choose File" style="display: none;" onchange="document.getElementById(&#039;guide-filecard-input&#039;).value = (this.files.length &lt;= 1) ? this.files[0].name : this.files.length + &#039; &#039; + &#039;files selected&#039;;">
			<div class="input-group">
				<div class="input-group-btn">
					<button type="button" onclick="document.getElementById('guide-filecard').click();" class="btn btn-default">Choose File</button>
				</div>
				<input type="text" name="guide.fileCard-text" class="form-control"  readonly="readonly" id="guide-filecard-input" onclick="document.getElementById(&#039;guide-filecard&#039;).click();" value="" />
			</div>
		</div>
	</div>\

The problem concerns the line:
    ``<button type="button" onclick="document.getElementById('guide-filecard').click();" class="btn btn-default">Choose File</button>``

Where you use the character `'` in `getElementById()` and that causes a `SyntaxError: missing ) after argument list`  error message.
Everywhere else, it's replaced by ``&#039; ``

Could you please fix it?

**Comment by Holt59** [comment]
I don't think it is a problem from the helper - You are outputing a string inside a javascript, you should probably encode it. Maybe you could try something like:

```js
'<div class="col-md-8">' 
+ <?= json_encode($this->FormB->input('guide.fileCard', ['label' => __("Télécharger votre carte"), 'type' => 'file'])); ?>
+ '</div>'
```

**Comment by 2ndGAB** [comment]
I tried it but the browser doesn't appreciate.
Please have a look at the other `getElementById()` calls in the generated code

**Comment by Holt59** [comment]
The `&#039;` are worse than the error actually... But `json_encode` should work in this case. 

I am guessing you are retrieving the generated code using *inspect*. Could you post the source code with and without `json_encode` (as obtained by `Right click > Source code` (not by inspecting elements)? Only the code generated for your `add_guide_card()` function.

**Comment by 2ndGAB** [comment]
Ok here is the code copied from source code:

	function add_guide_card() {
		$("#guide_card_infos").append(
			'<div id="guide_card" class="col-md-8">\
				<div class="alert alert-info" role="info">\
						<em>...</em>\
			    </div>\
			    <div class="col-md-4">\
			    	Votre carte : \
			    </div>\
			    <div class="col-md-8">\
			    	<div class="form-group file"><label class="control-label col-md-2"  for="guide-filecard">Télécharger votre carte</label><div class="col-md-10"><input type="file" name="guide[fileCard]"  id="guide-filecard" button-label="Choose File" style="display: none;" onchange="document.getElementById(&#039;guide-filecard-input&#039;).value = (this.files.length &lt;= 1) ? this.files[0].name : this.files.length + &#039; &#039; + &#039;files selected&#039;;"><div class="input-group"><div class="input-group-btn"><button type="button" onclick="document.getElementById('guide-filecard').click();" class="btn btn-default">Choose File</button></div><input type="text" name="guide.fileCard-text" class="form-control"  readonly="readonly" id="guide-filecard-input" onclick="document.getElementById(&#039;guide-filecard&#039;).click();" value="" /></div></div></div>\
		    	</div>\
			</div>');
			
	}

**Comment by Holt59** [comment]
Okay, so there was a very awful bug with the custom file input where the content was escaped by Cake... It should never have worked but I guess web browser are good at adapting bad codes... I should really make a `TestCase` for this input.

Anyway, this should be fixed by 522f2b48476cf3b42d20aab3762b16121b1ce685 - You should not see bad `&#039;` anymore with this update.

Back to your problem, you should still use `json_encode` to escape the output of `input()` like so (works for me with the update above):
```js
 function add_guide_card() {
     $("body").append(
         '<div class="col-md-8">'
       + <?= json_encode($this->Form->input('guide.fileCard',
                                            ['label' => __("Télécharger votre carte"),
                                             'type' => 'file'])); ?>
       + '</div>');
 }
```

**Comment by 2ndGAB** [comment]
Hmm well, I wonder if I well explained my problem because for me the issue remains.

In fact I didn't complained for the `&#039;` but the real `'` character and the ``json_encode()`` workaround doesn't help me here.

Without `json_encode()` the generated code is:

	$("#guide_card_infos").append(
		'<div id="guide_card" class="col-md-8">\
		    <div class="col-md-8">\
		    	<div class="form-group file"><label class="control-label col-md-2"  for="guide-filecard">Télécharger votre carte</label><div class="col-md-10"><input type="file" name="guide[fileCard]"  id="guide-filecard" button-label="Choose File" style="display: none;" onchange="document.getElementById(&#039;guide-filecard-input&#039;).value = (this.files.length &lt;= 1) ? this.files[0].name : this.files.length + &#039; &#039; + &#039;files selected&#039;;"><div class="input-group"><div class="input-group-btn"><button type="button" onclick="document.getElementById('guide-filecard').click();" class="btn btn-default">Choose File</button></div><input type="text" name="guide.fileCard-text" class="form-control"  readonly="readonly" id="guide-filecard-input" onclick="document.getElementById(&#039;guide-filecard&#039;).click();" value="" /></div></div></div>\
	    	</div>\
		</div>');

and with ``json_encode()``, accented characters are encoded but not the `'`. The generated code is:

	$("#guide_card_infos").append(
		'<div id="guide_card" class="col-md-8">\
		    <div class="col-md-8">\
		    	"<div class=\"form-group file\"><label class=\"control-label col-md-2\"  for=\"guide-filecard\">T\u00e9l\u00e9charger votre carte<\/label><div class=\"col-md-10\"><input type=\"file\" name=\"guide[fileCard]\"  id=\"guide-filecard\" button-label=\"Choose File\" style=\"display: none;\" onchange=\"document.getElementById(&#039;guide-filecard-input&#039;).value = (this.files.length &lt;= 1) ? this.files[0].name : this.files.length + &#039; &#039; + &#039;files selected&#039;;\"><div class=\"input-group\"><div class=\"input-group-btn\"><button type=\"button\" onclick=\"document.getElementById('guide-filecard').click();\" class=\"btn btn-default\">Choose File<\/button><\/div><input type=\"text\" name=\"guide.fileCard-text\" class=\"form-control\"  readonly=\"readonly\" id=\"guide-filecard-input\" onclick=\"document.getElementById(&#039;guide-filecard&#039;).click();\" value=\"\" \/><\/div><\/div><\/div>"\
	    	</div>\
		</div>');

In both cases, my problem comes from `document.getElementById('guide-filecard').click()`, not from `document.getElementById(&#039;guide-filecard&#039;).click()`

Is there a confusion between us?

**Comment by Holt59** [comment]
You did not follow my example - You need to concatenate the string using `+`, not use a multiline string with `\`.

 `json_encode` will give you a JSON string, together with the bounding `""`, so you cannot put it directly inside a multiline javascript string. If you have a php string, e.g. `$var = "Mr. 'Alain'"`, you have the following:

```js
var hello = 'Hello \
    <?= echo $var; ?> \
    !';
// ...is equivalent to:
var hello = 'Hello \
    Mr. 'Alain' \
    !';
```

Which obviously is not valid, but:

```js
var hello = 'Hello ' + <?= echo json_encode($var); ?> + '!';
// is equivalent to:
var hello = 'Hello ' + "Mr. 'Alain'" + '!';
```

Which is valid.

**Comment by 2ndGAB** [comment]
Ok sorry, you are right, I didn't know that.
Thanks a lot.

**Comment by Holt59** [comment]
I am closing this issue, feel free to open a new one if you have another problem with the custom file input!
