### ISSUE TITLE
Warning (2): Illegal string offset 'name'

### ISSUE THREAD

**Issue by doonot** [Holt59/cakephp3-bootstrap-helpers#96]
Since the new version we are getting this warning next to every file type input:

`Warning (2): Illegal string offset 'name' [ROOT/vendor/holt59/cakephp3-bootstrap-helpers/src/View/Helper/BootstrapFormHelper.php, line 416]`

How can we get rid of it?

**Comment by Holt59** [comment]
Do you have a default value for your file inputs? Or existing values given to the helper? As a temporary workaround you can replace the line 416 in `BootstrapFormHelper` by:

```php
'value' => isset($options['val']['name']) ? $options['val']['name'] : ''
```

**Comment by doonot** [comment]
No, no default value is provided:

`echo $this->Form->input('logo', [
                'type' => 'file',
                'id' => 'logo',
            ]);`

Your code above removes the warning. Will you add it in future version? Otherwise it will be overwritten when we update the library through composer.

Thank you very much!

**Comment by Holt59** [comment]
I will update the code as soon as I can, maybe with something more generic. Do you get these warnings with empty form and/or with filled form ? Also, what is the version of CakePHP you are using ?

**Comment by doonot** [comment]
Great, thanks.

Empty form:

`Warning (2): Illegal string offset 'name' [ROOT/vendor/holt59/cakephp3-bootstrap-helpers/src/View/Helper/BootstrapFormHelper.php, line 416]

Notice (8): Uninitialized string offset: 0 [ROOT/vendor/holt59/cakephp3-bootstrap-helpers/src/View/Helper/BootstrapFormHelper.php, line 416]`

Filled form:
`Warning (2): Illegal string offset 'name' [ROOT/vendor/holt59/cakephp3-bootstrap-helpers/src/View/Helper/BootstrapFormHelper.php, line 416]`

We are on the latest 3.x release (3.3.10 at the moment).

**Comment by lyz452** [comment]
#97 I fixed it while doing my other changes
