### ISSUE TITLE
Missing types in DocBlocks

### ISSUE THREAD

**Issue by nrother** [Holt59/cakephp3-bootstrap-helpers#98]
In all(?) `@param` annotations the type of the parameter is missing. This is not allowed according to the phpDoc specification and confuses IDEs like PHPStorm, they will interpret the first word of the description as the required type.

Example:

```
@param $icon Name of the icon.
```

PHPStorm now assumes that the parameter `$icon` has the type `Name` and the description is "of the icon". Correct version:

```
@param string $icon Name of the icon.
@param $icon string Name of the icon. //not recommended
```

**Comment by Holt59** [comment]
I started cleaning the documentation but there is still a lot to do. The current state should at least be valid according to phpDoc.

**Comment by nrother** [comment]
:+1: Looks much better now!

But somehow some code got messed up in the process around here: https://github.com/Holt59/cakephp3-bootstrap-helpers/commit/735e2171be72bf7cd548cde93bed45c877117465#diff-13772aef8b8cf654f9b688eaaa4e7ce3L297 This produces a warning because `$caret` is undefined and the Link is preceded with `">`

**Comment by Holt59** [comment]
I have fully cleaned the documentation for most helpers. Remaining are:

- `BootstrapFormHelper` - Needs to clean some of the `public` methods and all `protected` ones.
- `BootstrapModalHelper` - Need to add docs for all methods... ;)

**Comment by Holt59** [comment]
Everything should be ok now, I will put an HTML version of the API online as soon as I can (I am trying to work with [apigen](http://www.apigen.org/)). 

This will likely be up with the new documentation, feel free to contribute on the [mkdocs](https://github.com/Holt59/cakephp3-bootstrap-helpers/tree/mkdocs) branch!

**Comment by Holt59** [comment]
The API is now available online if you ever need it: http://holt59.github.io/cakephp3-bootstrap-helpers/api/
